name: black_jack
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

   
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/AC.png
    - Assets/AD.png
    - Assets/AH.png
    - Assets/AS.png
    - Assets/2C.png
    - Assets/2D.png
    - Assets/2H.png
    - Assets/2S.png
    - Assets/3C.png
    - Assets/3D.png
    - Assets/3H.png
    - Assets/3S.png
    - Assets/4C.png
    - Assets/4D.png
    - Assets/4H.png
    - Assets/4S.png
    - Assets/5C.png
    - Assets/5D.png
    - Assets/5H.png
    - Assets/5S.png
    - Assets/6C.png
    - Assets/6D.png
    - Assets/6H.png
    - Assets/6S.png
    - Assets/7C.png
    - Assets/7D.png
    - Assets/7H.png
    - Assets/7S.png
    - Assets/8C.png
    - Assets/8D.png
    - Assets/8H.png
    - Assets/8S.png
    - Assets/9C.png
    - Assets/9D.png
    - Assets/9H.png
    - Assets/9S.png
    - Assets/10C.png
    - Assets/10D.png
    - Assets/10H.png
    - Assets/10S.png
    - Assets/JC.png
    - Assets/JD.png
    - Assets/JH.png
    - Assets/JS.png
    - Assets/KC.png
    - Assets/KD.png
    - Assets/KH.png
    - Assets/KS.png
    - Assets/QC.png
    - Assets/QD.png
    - Assets/QH.png
    - Assets/QS.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
